# Generated by Django 5.0.1 on 2024-02-16 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID pour identifier l'auteur",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Le nom de l'auteur", max_length=100),
                ),
                (
                    "biography",
                    models.TextField(
                        help_text="La biographie de l'auteur", max_length=1000
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="La date de création de l'auteur"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="La date de mise à jour de l'auteur"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID pour identifier le genre",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Le nom du genre", max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="La date de création du genre"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="La date de mise à jour du genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID pour identifier le livre",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Titre du livre", max_length=100)),
                (
                    "summary",
                    models.TextField(help_text="le résumé du livre", max_length=1000),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Le prix du livre", max_digits=6
                    ),
                ),
                (
                    "num_pages",
                    models.IntegerField(help_text="Le nombre de pages du livre"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="L'image de couverture du livre",
                        upload_to="book_covers/",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(help_text="La date de publication du livre"),
                ),
                (
                    "availibility",
                    models.BooleanField(help_text="La disponibilité du livre"),
                ),
                (
                    "recommended_number",
                    models.IntegerField(
                        help_text="Le nombre de fois que le livre a été recommmandé"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="La date de création du livre"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="La date de mise à jour du livre"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="l'id de l'auteur du livre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Catalogue.author",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="l'id du genre du livre", to="Catalogue.gender"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID pour identifier le commentaire",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Le contenu du commentaire", max_length=1000
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="La date de création du commentaire",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="La date de mise à jour du commentaire"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="L'id du livre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Catalogue.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="L'id de l'utilisateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
