# Generated by Django 5.0.2 on 2024-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default=None, help_text='le résumé du livre'),
        ),
    ]
