# Generated by Django 5.0.2 on 2024-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0003_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, help_text="L'image de couverture du livre", upload_to='book_covers'),
        ),
    ]
