# Generated by Django 5.0.2 on 2024-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0005_alter_author_biography_alter_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
