# Generated by Django 5.0.1 on 2024-02-23 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0005_alter_author_biography_alter_author_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID pour identifier la réponse', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Le contenu de la réponse', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='La date de création de la réponse')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='La date de mise à jour de la réponse')),
                ('comment', models.ForeignKey(help_text="L'id du commentaire", on_delete=django.db.models.deletion.CASCADE, to='Catalogue.comment')),
                ('user', models.ForeignKey(help_text="L'id de l'utilisateur", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
