# Generated by Django 5.0.1 on 2024-02-23 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Catalogue", "0006_answer"),
        ("Catalogue", "0006_lbook"),
    ]

    operations = []
